# Site
repository: alisha1221/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alisha Rajbhandari
title: Data Scientist
email: alisha.rjb@gmail.com
website: www.github.com/alisha1221

# Dark Mode (true/false/never)
darkmode: false

# Social links
##twitter_username: facespics
github_username:  alisha1221
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
##instagram_username: jameswgrant
linkedin_username: rjb-alisha
# xing_username: jekyll
# pinterest_username: jekyll
##youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
## - title: another link
##   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
##   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/linkedin_pic2.png
about_content: | # this will include new lines to allow paragraphs
  I am a data scientist with 4+ years of experience working in the research industry with proven problem solving, research, analytical, and communication skills. I collaborate with cross-functional teams to analyze data and generate meaningful insights from them using various tools and models. I am passionate about learning new things and have experience working in diverse set of projects related to healthcare, defense, environmental, epigenetics, clinical trials, and biostatistics.   

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
#
  - title: Key Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>SAS</mark>, <mark>Python</mark>, <mark>R</mark>, <mark>R-Shiny</mark>, <mark>R-Markdown</mark>, <mark>SQL</mark>
      - Advanced knowledge in <mark>Microsoft Office</mark> suite (including Pivot Tables, LOOKUP, and Macros)
      - Building a pipeline from data collection, extraction and verification with building various machine learning, deep learning models and then presenting meaningful results on Dashboard
      - Actuarial Exams Passed: <mark>P, FM, MFE, C, VEE</mark>
      - Experienced with version control tools like <mark>GitHub</mark>, <mark>Gitlab</mark>, <mark>SVN</mark>
      - Experienced working on High Performance Computing along with cloud-computing platform like Amazon Web Services (<mark>AWS</mark>)
   
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Battelle Memorial Institute
        link: battelle.org
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: January 2019 - December 2022
        # quote: >
        #   Battelle is an independent not-for-profit organization that advances science and technology to have the greatest impact on our society and economy.
        description: | # this will include new lines to allow paragraphs
            - Worked with the analytics team in supporting government and private industry clients in the healthcare, defense, and environmental sectors.
            - Implemented and tested methodologies to solve various problems using machine learning/deep learning models.
            - Performed statistical analysis and modeling, generated graphical displays, managed data, and prepared supporting documentations for a variety of tasks.
            - Managed micro projects by developing scope and project plans, providing team leadership, monitoring schedules, costs and quality of project as well as carrying out the data analysis.
            - Automated the data cleaning process along with EDA to produce ~2800 pages of statistical results and plots with a single click.
            - Built a pipeline in predicting labor hours required for different tasks in a project and deployed using Shiny Dashboard.
            - Developed data science standards for the biostatistics team and led the efforts for transitioning to GitHub.
            - Automated multiple tasks to reduce time in multiple projects by efficient coding strategies.
            - Contributed to delivering the dataset, codebook, data dictionary and documentations.
            - Communicated efficiently with internal and external clients in describing technical results in a clear and succinct manner in the form of presentations and technical reports.
            - Contributed to several peer-reviewed journal publications and conference presentations.
            - Supported business development efforts by contributing to technical sections of the proposals.
            - Worked in a fast-paced environment with multiple projects and met deadlines.
            - Worked independently as well as in teams, including leading and mentoring staffs.

      - layout: left
        title: Procter & Gamble
        link: us.pg.com
        # link_text: boringcompany.com
        sub_title: Data and Modeling Sciences Intern
        caption: August 2018 - December 2018
        # quote: >
        #   Battelle is an independent not-for-profit organization that advances science and technology to have the greatest impact on our society and economy.
        description: | # this will include new lines to allow paragraphs
            - Analyzed various structured and unstructured data using advanced statistical modeling techniques
            - Evaluated consumer product usage results and developed statistical webtools for effective data visualization using R Shiny, R Markdown and SAS
            
      - layout: left
        title: Ameritas Life Insurance Corporation
        link: ameritas.com
        # link_text: boringcompany.com
        sub_title: Actuarial Intern
        caption: May 2018 - August 2018
        # quote: >
        #   Battelle is an independent not-for-profit organization that advances science and technology to have the greatest impact on our society and economy.
        description: | # this will include new lines to allow paragraphs
            - Reviewed reinsurance treaties between Ameritas and other reinsurance companies to confirm that the reinsurance is being administered properly
            - Computed premiums using paper-based treaty agreement and compared to the premiums from the reinsurance administration system
            - Communicated findings from the treaty review process to supervisors
            - Automated the treaty review process for survivorship policies using Excel VBA

      - layout: left
        title: Miami University
        link: miamioh.edu
        # link_text: boringcompany.com
        sub_title: Graduate Assistant
        caption: August 2017 - December 2018
        # quote: >
        #   Battelle is an independent not-for-profit organization that advances science and technology to have the greatest impact on our society and economy.
        description: | # this will include new lines to allow paragraphs
            - Led lab sessions for introductory statistics courses 
            - Held office hours and helped students understand more about the statistics
            - Graded homeworks, quizzes, exams, labs, and proctored exams

      - layout: left
        title: University of Texas at Tyler
        link: www.uttyler.edu
        # link_text: boringcompany.com
        sub_title: Grader
        caption: September 2015 - May 2016
        # quote: >
        #   Battelle is an independent not-for-profit organization that advances science and technology to have the greatest impact on our society and economy.
        description: | # this will include new lines to allow paragraphs
            - Graded the assignments and quizzes for Calculus and Statistics courses for the Mathematics department
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Miami University
        caption: 2017 - 2019
        sub_title: MS Statistics
        #quote: >
        #  Established in 1809, Miami University is the second-oldest university in Ohio and was one of the original eight Public Ivy schools, a group of publicly funded universities considered as providing a quality of education comparable to those of the Ivy League.
        description: | # this will include new lines to allow paragraphs -- During my time at Miami I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I  was a *graduate assistant* at Miami and spent two semesters leading lab sessions for statistics courses for the undergraduate students. I also worked as a statistical consultant for the *Practicuum in Data Analysis* coursework and gained hands-on experience working with real data and communicating results to the clients.

      - layout: left
        title: University of Texas at Tyler
        caption: 2015 - 2016
        sub_title: Mathematics, Non-degree
        #quote: >
        #  Established in 1809, Miami University is the second-oldest university in Ohio and was one of the original eight Public Ivy schools, a group of publicly funded universities considered as providing a quality of education comparable to those of the Ivy League.
        description: | # this will include new lines to allow paragraphs
          I took some mathematics courses to fulfil the prerequisites for MS Statistics program.

      - layout: left
        title: Pokhara University
        caption: 2010 - 2014
        sub_title: Bachelor of Business Administration
        #quote: >
        #  Established in 1809, Miami University is the second-oldest university in Ohio and was one of the original eight Public Ivy schools, a group of publicly funded universities considered as providing a quality of education comparable to those of the Ivy League.
        description: | # this will include new lines to allow paragraphs
          During my undergraduate years, I took data analysis and modeling course, which piqued my interest in this field. I was intrigued by how we can analyze historical data to gain insights into the future and make data driven decisions. This led me to pursue actuarial exams and take advanced mathematics courses.


  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs 
     - **Rajbhandari, A.**, Matteson, K., Katz, E., LeBuhn, G., & Johnson, E. (2023). **Bee visitation to flowers throughout New York City**. Landscape and Urban Planning, 233, 104689.
     - Kim, H., **Rajbhandari, A.**, Krile, R., Lang, I. M., Antonakos, C. L., & Colabianchi, N. (2023). **Body Mass Index Trajectories among the Healthy Communities Study Children: Racial/Ethnic and Socioeconomic Disparities in Childhood Obesity**. Journal of racial and ethnic health disparities, 1â€“13. Advance online publication. https://doi.org/10.1007/s40615-023-01511-x
     - Schuetter J, Johnson C, **Rajbhandari A**, Bollas A, Fair A, et al. (2022) **The case for targeted community level pathogen genomic biosurveillance and visualization in the Wastewater Pathogen Tracking Dashboard**. Arch Epid Pub Health 4: DOI: 10.15761/AEPH.1000126. 
     -  Niemuth NA, Fallacara D, Triplett CA, Tamrakar SM, **Rajbhandari A**, Florence C, et al. (2021) **Natural history of disease in cynomolgus monkeys exposed to Ebola virus Kikwit strain demonstrates the reliability of this non-human primate model for Ebola virus disease**. PLoS ONE 16(7): e0252874. https://doi.org/10.1371/journal.pone.0252874 


  - title: Presentations
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Stewart, M.T., **Rajbhandari, A.**, Lang, I-M., Miller, S., Colabianchi, N. (2021). Neighborhood safety, school programming, and active transportation to school; findings from the Healthy Communities Study (Mini-Oral). 8th International Society for Physical Activity and Health (ISPAH) Congress, held Virtual due to COVID-19. October, 2021.
      - Stewart, M.T., Verma, M., **Rajbhandari, A.**, Antonakos, C., Colabianchi, N. (2021). Park Availability and Physical Activity Among Children and Adolescents: Findings from the Healthy Communities Study. International Conference on Ambulatory Monitoring of Physical Activity and Movement. Virtual Conference. June, 2021.
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
